### DISCUSSION TITLE
Cannot find correct value for TRAEFIK_POLL_URL

### DISCUSSION THREAD

**Discussion by alejakun** [tiredofit/docker-traefik-cloudflare-companion#60] [Q&A]
As the title states, I'm trying to setup Traefik Poll, everything seems to be working otherwise, but can't seem to be able to provide a correct value for TRAEFIK_POLL_URL.

**Comment by DrDirtyDevil** [comment]
i got mine working with http://traefik:8080/

**Reply by alejakun** [reply]
Hi,

Would you be so kind to share a docker-compose example, mine seems to not be working (it gives me no errors, but also will not update the cloudflare dns. Here's how mine looks like:

```
  cf-companion:
    image: tiredofit/traefik-cloudflare-companion
    container_name: cf-companion
    restart: always
    security_opt:
      - no-new-privileges:true
    secrets:
      - cf_email
      - cf_token
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TIMEZONE: $TZ
      CF_EMAIL: /run/secrets/cloudflare_email
      CF_TOKEN: /run/secrets/cloudflare_api_key
      TARGET_DOMAIN: proxy.$DOMAIN_NAME
      DOMAIN1: $DOMAIN_NAME
      DOMAIN1_ZONE_ID: $CLOUDFLARE_ZONE_ID
      DOMAIN1_PROXIED: "FALSE"
      TRAEFIK_VERSION: 2
      ENABLE_TRAEFIK_POLL: "TRUE"
      TRAEFIK_POLL_URL: http://traefik:8080/
      TRAEFIK_POLL_SECONDS: 60
```

By the way, I've already tested that the Traefik_poll_url is accessible and redirects to the dashboard, which I think is the meaning of that address (it automatically redirects to the dashboard).

Best regards.
