### ISSUE TITLE
SyntaxError: invalid syntax. Perhaps you forgot a comma?

### ISSUE THREAD

**Issue by burnbrigther** [tiredofit/docker-traefik-cloudflare-companion#106]
### Summary

In latest version, new error introduced.

```
2024-06-24T18:31:52.264662694Z SyntaxError: invalid syntax. Perhaps you forgot a comma?
2024-06-24T18:31:53.303132972Z 2024-06-24.11:31:53 [STARTING] ** [traefik-cloudflare-companion] [51] Starting Traefik Cloudflare Companion
2024-06-24T18:31:53.318834335Z   File "/usr/sbin/cloudflare-companion", line 183
2024-06-24T18:31:53.318854618Z     u'proxied': domain_info['proxied']
2024-06-24T18:31:53.318859114Z                 ^^^^^^^^^^^^^^^^^^^^^^
```

### Steps to reproduce

1. Install latest update on docker (docker container pull)
2. Start with new image
3. Check logs

### What is the expected *correct* behavior?

No error, functionality restored.  Updates are still not working.

### Relevant logs and/or screenshots

See above

### Environment
docker on a privileged VM
Latest version of cf-companion

- Image version / tag:  latest
- Host OS: Linux myhost 5.15.0-112-generic #122-Ubuntu SMP Thu May 23 07:48:21 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

<details>
<summary>Any logs | docker-compose.yml</summary>

```
services:
# Cloudflare-Companion - Automatic CNAME DNS Creation
  cf-companion:
    container_name: cf-companion
    image: tiredofit/traefik-cloudflare-companion:latest
    restart: always
    profiles: ["core", "security", "all"]
    networks:
      - socket_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TIMEZONE=$TZ
      - TRAEFIK_VERSION=2
      - CF_TOKEN=$CLOUDFLARE_SUPER_API_KEY # Same as traefik
      - TARGET_DOMAIN=$DOMAINNAME_1
      - DOMAIN1=$DOMAINNAME_1
      - DOMAIN1_ZONE_ID=$CLOUDFLARE_ZONEID # Copy from Cloudflare Overview page
      - DOMAIN1_PROXIED=TRUE
    labels:
      # Add hosts specified in rules here to force cf-companion to create the CNAMEs
      # Since cf-companion creates CNAMEs based on host rules, this a workaround for non-docker/external apps
#      - "traefik.http.routers.cf-companion-rtr.rule=Host(`my-host.$DOMAINNAME_1`) || Host(`my-host.$DOMAINNAME_2`)"
      - "traefik.http.routers.cf-companion-rtr.rule=Host(`my-host.$DOMAINNAME_1`)"
      - "diun.enable=true"
```

ERROR:
```
SyntaxError: invalid syntax. Perhaps you forgot a comma?
2024-06-24.11:37:21 [STARTING] ** [traefik-cloudflare-companion] [68] Starting Traefik Cloudflare Companion
  File "/usr/sbin/cloudflare-companion", line 183
    u'proxied': domain_info['proxied']
                ^^^^^^^^^^^^^^^^^^^^^^
```
</details>

I tried both single domain and dual-domain configuration, as shown in the commented configuration code with same resulting error.
