### ISSUE TITLE
Support for defaultRule

### ISSUE THREAD

**Issue by Mbarmem** [tiredofit/docker-traefik-cloudflare-companion#11]
Instead of defining Host label under each service, i have a default rule in the traefik.yml configuration as shown below:

```
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    swarmMode: false
    network: traefik_2
    defaultRule: "Host(`{{ index .Labels \"com.docker.compose.service\"}}.domain.com`)"
```
Is their any work around for this scenario or possibility to add support?
