### ISSUE TITLE
insane cpu usage while doing nothing

### ISSUE THREAD

**Issue by warlordattack** [tiredofit/docker-traefik-cloudflare-companion#110]
Hello, 

I run this in rocky linux proxmox vm, with podman,

```
version: '3'
services:
  srv_traefik_clc:
    container_name: ${C_TFC}
    image: ${C_TFC_IMG}
    restart: ${C_ALL_RESTART}
    hostname: ${C_TFC_HOST} 
    environment:
      - TIMEZONE=${TZ}
      - TRAEFIK_POLL_SECONDS=120
      - LOG_TYPE=BOTH
      - LOG_LEVEL=INFO
      - TRAEFIK_VERSION=2
      - CF_EMAIL=${CF_EMAIL}
      - CF_TOKEN=${CF_API_KEY}
      - RC_TYPE=CNAME
      #
      - TARGET_DOMAIN=${DOM}
      #
      - DOMAIN1=${DOM}
      - DOMAIN1_ZONE_ID=${CF_API_ZONE_ID}
      - DOMAIN1_EXCLUDED_SUB_DOMAINS=l # exclude *.l.domain.ext
      - DOMAIN1_PROXIED=True
    volumes:
      - ${REP_APPDATA}/${C_TFC}/logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
    networks:
      - default
networks:
  default:
    external:
      name: $NET_TFK
```

Everything looks pretty good except two errors at start, records are created at container start, but not sure it really polls every 120 seconds, i do not see log moving
![image](https://github.com/user-attachments/assets/a29ff21a-0471-4689-bc70-dee793d9f393)

So i let container run normally, portainer view shows some IO (for 35mb ???), and no CPU usage : 
![image](https://github.com/user-attachments/assets/58414ccf-c004-4c55-9611-6fea4d14c868)

But my Dozzle shows some strange CPU activity highest of 40 other containers : 
![image](https://github.com/user-attachments/assets/5fe4285a-311f-4497-a6f9-ad9e30baf162)

So i do BTOP on the rocky VM, and you can observe an insane python3 CPU usage (89%) related to cloudflare companion : 
![image](https://github.com/user-attachments/assets/3552952b-66b5-4f4b-9055-936e3945799a)

Now i stop cloudflare-companion container, and my CPU usage is instantly back to normal : 
![image](https://github.com/user-attachments/assets/88816143-6c85-4e45-996e-2d185151e4d7)

There is something not normal there, some bitcoin mining in the backgroung ?
Please fix this.

Best regards :)
