### ISSUE TITLE
No CNAME's records added

### ISSUE THREAD

**Issue by Blood13** [tiredofit/docker-traefik-cloudflare-companion#22]
Hello :)
Docker swarm + dtcc 6.0.1
```
[INFO] ** [zabbix] Starting Zabbix Agent
zabbix_agentd [743]: Warning: EnableRemoteCommands parameter is deprecated, use AllowKey=system.run[*] or DenyKey=system.run[*] instead
Starting Zabbix Agent [alpine]. Zabbix 5.0.2 (revision {ZABBIX_REVISION}).
Press Ctrl+C to exit.


[debug] Swarm Mode: true
[debug] Refresh Entries: false
[debug] Traefik Version: 1
[debug] Default TTL: 1
```
Nothing happens.
```
environment:
      TRAEFIK_VERSION: 1
      CF_EMAIL: email
      CF_TOKEN: token
      DOMAIN1: domain
      DOMAIN1_ZONE_ID: zoneId
      DOMAIN1_PROXIED: "true"
      TARGET_DOMAIN: target
      SWARM_MODE: "true"
      REFRESH_ENTRIES: "false"
      CONTAINER_LOG_LEVEL: DEBUG
```
Also it would be nice if script will listen docker sock for not just "start" event, but for "update" (if it possible) too, because `docker stack deploy` trigger "update" (`Updating service ...`) if service already exist.

**Comment by tiredofit** [comment]
Please try with uppercase variables? 
I can certainly look into the update trigger.

**Comment by Blood13** [comment]
Doesn't help
```
Press Ctrl+C to exit.


[debug] Swarm Mode: TRUE
[debug] Refresh Entries: FALSE
[debug] Traefik Version: 1
[debug] Default TTL: 1
```

**Comment by tiredofit** [comment]
Thanks. Let me look into - Might want to stick with 5.0.0 for time being until I get this sorted.

**Comment by Blood13** [comment]
Sure, no problem.

**Comment by tiredofit** [comment]
I'm having a look at this now, and not seeing the same results you are. You are probably much more advanced with your swarm knowledge than I am, this is how I am doing it.

`docker service create --replicas 1 --container-label traefik.enable=true --container-label traefik.http.routers.hello-world.rule=Host\(\`foo.example.ca\`\) --name helloworld alpine ping docker.com 
`

Image output: 
````bash
Found Container: e0ecda48a22f5bdd5eab89ce1c590d8caceef8685a9624d25f788c50b372cdae with Hostname foo.example.ca
Created new record: foo.example.ca to point to home.example.ca
````

docker inspect helloworld: (only the stuff that matters)

````bash
        "Spec": {
            "Name": "helloworld",
            "Labels": {},
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "alpine:latest@sha256:185518070891758909c9f839cf4ca393ee977ac378609f700f60a771a2dfe321",
                    "Labels": {
                        "traefik.enable": "true",
                        "traefik.http.routers.hello-world.rule": "Host(`foo.example.ca`)"
                    },
                    "Args": [
                        "ping",
                        "docker.com"
                    ],
````

**Comment by tiredofit** [comment]
Wow, I spent a considerable amount of time trying to unpack what the heck Swarm is doing. 

I've added to the `tiredofit/traefik-cloudflare-companion:develop` image the following:

- Update Event Support
- A different way of going about doing Swarm lookups
- Waaaay more debugging info to tell where the heck things are going on.

Would you be able to give this a test and let me know if we're in good shape now?

**Comment by DrevanTonder** [comment]
I might be able to help.

I'm having the same issue with docker swarm (cloudflare companion not detecting the Hosts).

Having a look at the code in `install/usr/sbin/cloudflare-companion` line 148 (and 149) in `check_service_t2` it uses:
```python
s.attrs.get(u'Spec').get(u'TaskTemplate').get(u'ContainerSpec').get(u'Labels')
```

It's looking at the container for the label.

When you use Traefik with Docker Swarm you define the labels on the service:
https://doc.traefik.io/traefik/providers/docker/#configuration-examples
```yaml
version: "3"
services:
  my-container:
    deploy:
      labels:
        - traefik.http.routers.my-container.rule=Host(`example.com`)
        - traefik.http.services.my-container-service.loadbalancer.server.port=8080
```

These labels then get applied to the service **not the container**.

So, it should probably be:
```python
s.attrs.get(u'Spec').get(u'Labels')
```
