### ISSUE TITLE
Don't work with SWARM_MODE

### ISSUE THREAD

**Issue by kyusupov33** [tiredofit/docker-traefik-cloudflare-companion#42]
Hi, thank for your great solution. Please, explain why container does not watching swarm cluster and updating cloudflare cnames?
```
version: '3.5'

services:
  traefik-cloudflare-companion:
    image: tiredofit/traefik-cloudflare-companion
    networks:
      - {{ monitoring_network_name }}
      - {{ traefik_network_name }}
      - internal
    environment:
      - TIMEZONE={{ TZ }}
      - TRAEFIK_VERSION="2"
      - CF_EMAIL={{ cf_api_email }}
      - CF_TOKEN={{ cf_api_key }}
      - TARGET_DOMAIN={{ app_domain_name }}
      - DOMAIN1={{ app_domain_name }}
      - DOMAIN1_ZONE_ID={{ cf_api_zone }}
      - DOMAIN1_PROXIED="TRUE"
      - SWARM_MODE="TRUE"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  {{ monitoring_network_name }}:
    driver: overlay
    attachable: true
    name: {{ monitoring_network_name }}
  {{ traefik_network_name }}:
    external: true
    name: {{ traefik_network_name }}
  internal:
    external: false

```
