### ISSUE TITLE
Healthcheck Option

### ISSUE THREAD

**Issue by jwillmer** [tiredofit/docker-traefik-cloudflare-companion#47]
Is there a possibility to use healthchecks like:

```
    healthcheck:
      test: wget --spider http://localhost || exit 1
      interval: "30s"
      timeout: "5s"
      retries: 3
      start_period: "15s"
```
