### ISSUE TITLE
Constant Authentication Errors

### ISSUE THREAD

**Issue by mariaWitch** [tiredofit/docker-traefik-cloudflare-companion#73]
### Summary

When I add a new domain to a container through traefik, cloudflare-companion errors out repeatedly with authentication failures to cloudflare. I'm not sure if something has changed with Cloudflare's API, but both of my other services which rely on the same API keys/tokens do not have the same issue as this does.

### Steps to reproduce

(Input your api keys and tokens, and then attempt to start the container with a host set to a subset of the domain.)

### What is the expected *correct* behavior?

It should not error and should create the subdomain automatically.

### Relevant logs and/or screenshots

```
cloudflare-companion    | 2022-08-14.15:59:38 [STARTING] ** [traefik-cloudflare-companion] [19] Starting Traefik Cloudflare Companion
cloudflare-companion    | Traceback (most recent call last):
cloudflare-companion    |   File "/usr/sbin/cloudflare-companion", line 466, in <module>
cloudflare-companion    |     sync_mappings(get_initial_mappings(traefik_included_hosts, traefik_excluded_hosts), doms)
cloudflare-companion    |   File "/usr/sbin/cloudflare-companion", line 354, in sync_mappings
cloudflare-companion    |     if point_domain(k, domain_infos):
cloudflare-companion    |   File "/usr/sbin/cloudflare-companion", line 168, in point_domain
cloudflare-companion    |     records = cf.zones.dns_records.get(domain_info['zone_id'], params={u'name': name})
cloudflare-companion    |   File "/usr/lib/python3.10/site-packages/CloudFlare/cloudflare.py", line 695, in get
cloudflare-companion    |     return self._base.call_with_auth('GET', self._parts,
cloudflare-companion    |   File "/usr/lib/python3.10/site-packages/CloudFlare/cloudflare.py", line 139, in call_with_auth
cloudflare-companion    |     return self._call(method, headers, parts,
cloudflare-companion    |   File "/usr/lib/python3.10/site-packages/CloudFlare/cloudflare.py", line 525, in _call
cloudflare-companion    |     raise CloudFlareAPIError(code, message)
cloudflare-companion    | CloudFlare.exceptions.CloudFlareAPIError: Authentication error
```

### Environment

- Image version / tag:  6.8.5
- Host OS: Proxmox VE 7.2-7
- Guest OS: Almalinux 8.6 x86_64

<details>
<summary>docker-compose.yml</summary>

```
version: "3.7"
networks:
  internal:
    driver: bridge
  services:
    driver: bridge
  keycloakDB:
    driver: bridge
volumes:
  traefik-logs:
services:
  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    network_mode: "host"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./CloudflareDDNS/config.json:/config.json:ro
    restart: unless-stopped
  cloudflare-companion:
    image: tiredofit/traefik-cloudflare-companion:latest
    container_name: cloudflare-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TRAEFIK_VERSION=2
      - CF_EMAIL=<Redacted>
      - CF_TOKEN=<Redacted>
      - TARGET_DOMAIN=ddns.domain.tld
      - DOMAIN1=domain.tld
      - DOMAIN1_PROXIED=true
      - DOMAIN1_ZONE_ID=<Redacted>
      #- DOCKER_HOST=tcp://198.51.100.32:2376
      #- DOCKER_CERT_PATH=/docker-certs
      #- DOCKER_TLS_VERIFY=1
    networks:
      - internal
      - services
    restart: unless-stopped
  KCPostgres:
    image: bitnami/postgresql:14
    container_name: keycloakDB
    restart: unless-stopped
    networks:
      - keycloakDB
    volumes:
      - ./postgres/data/postgres_data:/bitnami/postgresql/
    ports:
      - 5432:5432
    env_file:
      - ./postgres/KCpostgres.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U <Redacted>"]
      interval: 10s
      timeout: 5s
      retries: 5
  KCPBackup:
      image: bitnami/postgresql:14
      container_name: KCDBBackup
      networks: 
        - keycloakDB
      volumes:
        - ./postgres/data/backup/:/dump/
      restart: unless-stopped
      environment:
        - PGHOST=KCPostgres
        - PGUSER=<redacted>
        - PGPASSWORD=<redacted>
        - BACKUP_NUM_KEEP=7
        - BACKUP_FREQUENCY=1d
      entrypoint: |
        bash -c 'bash -s <<EOF
        trap "break;exit" SIGHUP SIGINT SIGTERM
        sleep 2m
        while /bin/true; do
          pg_dump -Fc > /dump/dump_\`date +%d-%m-%Y"_"%H_%M_%S\`.psql
          (ls -t /dump/dump*.psql|head -n $$BACKUP_NUM_KEEP;ls /dump/dump*.psql)|sort|uniq -u|xargs rm -- {}
          sleep $$BACKUP_FREQUENCY
        done
        EOF'
      depends_on:
        KCPostgres:
          condition: service_healthy
  traefik:
      image: traefik:vacherin
      container_name: traefik
      restart: unless-stopped
      security_opt:
        - no-new-privileges:true
      networks:
        - services
      ports:
        - 80:80
        - 443:443
        - 8080:8080
      environment:
        - CF_API_EMAIL=<Redacted>
        #- CF_API_KEY=<Redacted>
        - CF_DNS_API_TOKEN=<Redacted>
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./Traefik/data/traefik.yml:/traefik.yml:ro
        - ./Traefik/data/acme.json:/acme.json
        - ./Traefik/data/config.yml:/config.yml:ro
        - ./Traefik/data/log:/var/log/traefik
      labels:
        - traefik.enable=true
        - traefik.http.routers.traefik.entrypoints=http
        - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
        - traefik.http.middlewares.redirect-to-https.redirectscheme.port=443
        - traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)
        - traefik.http.routers.redirs.entrypoints=http
        - traefik.http.routers.redirs.middlewares=redirect-to-https
        - traefik.http.routers.dashboard.rule=Host(`traefik.domain.tld`)
        - traefik.http.services.dashboard.loadbalancer.server.port=8080
        

```
</details>

**Comment by mariaWitch** [comment]
I figured out the issue, you apparently need to point CF_TOKEN to your global API key not your API_Token for the specific zone and Domain. Perhaps clarifiying this on the instructions would prevent people from encountering this issue.

**Comment by tigerkzr** [comment]
> I figured out the issue, you apparently need to point CF_TOKEN to your global API key not your API_Token for the specific zone and Domain. Perhaps clarifiying this on the instructions would prevent people from encountering this issue.

just want to note that you have to put the global API key in a file call "cf_token".  Like an idiot, I kept trying to point my cf_api_key file at the CF_TOKEN env var...

**Comment by JohnYangSam** [comment]
I couldn't seem to get the token working, but was able to get it working with the following, although it does not look like `CF_API_KEY` is referenced in the readme documentation:
```
environment:
    # See: https://developers.cloudflare.com/fundamentals/api/get-started/keys/
    - CF_API_KEY=<Cloudflare Global API Key>
    - CF_API_EMAIL=<Email for Cloudflare>
````

**Comment by JohnYangSam** [comment]
For what it is worth, I was able to get the companion working with only the scoped `CF_TOKEN` (more secure than the Global API key method).

I believe the key was making sure that the `CF_API_EMAIL` was not also set at the same time.

Here is the service file and an example Cloudflare configuration for those who come across this in the future:

docker-compose.yml snippet: 

```
cloudflare-companion:
    image: ghcr.io/tiredofit/docker-traefik-cloudflare-companion:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: any
        delay: 3s
      placement:
        constraints:
          - node.role == manager

    environment:
      - TIMEZONE=America/New_York

      - LOG_TYPE=CONSOLE
      - LOG_LEVEL=INFO

      # This should work with Traefik version 3 as well
      - TRAEFIK_VERSION=2
      - RC_TYPE=CNAME

      # Target in Cloudflare where DNS records will be pointed
      - TARGET_DOMAIN=${SUBDOMAIN}${ROOT_DOMAIN}

      - REFRESH_ENTRIES=TRUE
      # Enable swarm
      - DOCKER_SWARM_MODE=TRUE

      # Poll the traefik API for changes. Make sure the traefik API is enabled.
      # /api doesn't return anything. Instead if you have the traefik dashboard enabled
      # and the ports open on local host, you can test with:
      # curl http://localhost:8080/api/http/routers
      - ENABLE_TRAEFIK_POLL=TRUE
      # traefik is the service name of the traefik service
      - TRAEFIK_POLL_URL=http://traefik:8080/api

      # Services with the label: traefik.constraint=traefik-public will have domains added to Cloudflare
      - TRAEFIK_FILTER_LABEL=traefik.constraint
      - TRAEFIK_FILTER=traefik-public

      # Domain we want to edit (this is the main domain, not subdomain) and the
      # corresponding zone ID in Cloudflare found on the domain's DNS overview page in the
      # bottom right corner.
      - DOMAIN1=${ROOT_DOMAIN}
      - DOMAIN1_ZONE_ID=${CLOUDFLARE_ZONE_ID}
      - DOMAIN1_PROXIED=TRUE
      # Overrides the TARGET_DOMAIN for this domain
      - DOMAIN1_TARGET_DOMAIN=${SUBDOMAIN}${ROOT_DOMAIN}
      # This is an alternative where we forward to the tunnel instead of the root domain (then tunnel)
      #- DOMAIN1_TARGET_DOMAIN=${CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com


      # Instructions (this can be very finicky) for getting the DNS API token to work:
      # 1. Go to Cloudflare Profile -> API Tokens -> Create Token. See: https://dash.cloudflare.com/profile/api-tokens
      # 2. Create Custom token with the following permissions:
      #      Token name: <domain name> DNS:Edit and DNS:Read
      #      Zone:Zone:Read
      #      Zone:DNS:Edit
      # 3. Copy the token and paste it into the .env file as CLOUDFLARE_DNS_API_TOKEN
      #
      # If you use this method, DO NOT uncomment the CF_API_EMAIL and CF_API_KEY lines below.
      # Adding the email will cause the companion to think that you're trying to use the
      # global API key method instead.
      - CF_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}

      # Alteratnive to CF_TOKEN:Cloudflare API credentials
      #- CF_API_EMAIL=${CLOUDFLARE_GLOBAL_API_EMAIL}
      # DIFFERENT than the DNS API token
      # See: https://github.com/tiredofit/docker-traefik-cloudflare-companion/issues/73#issuecomment-1214935490
      #- CF_API_KEY=${CLOUDFLARE_GLOBAL_API_KEY}

    networks:
      - app-network
```

Cloudflare API Token Configuration:

![Image](https://github.com/user-attachments/assets/6f025178-725a-4b00-bf15-8d4e342fcf57)
