### ISSUE TITLE
Container specific proxied status

### ISSUE THREAD

**Issue by indykoning** [tiredofit/docker-traefik-cloudflare-companion#93]
**Description of the feature**
It would be great to be able to override the default configuration per subdomain on the Docker container.
e.g. using labels
```yaml
labels:
  traefik.enable: true
  traefik.network: public
  traefik.http.routers.appname.rule: Host(`appname.example.com`)
  traefik.http.routers.appname.cloudflare.proxied: false
```

**Benftits of feature**
This will make it possible/much easier to have different rules set for different applications.
As some (e.g. Nextcloud and Jellyfin) can not adhere to the TOS and are not eligible for proxying
